### ISSUE TITLE
Port forwarding? What is it, 2007?

### ISSUE THREAD

**Issue by nikolai-imversed** [DFJacob/AbioticFactorDedicatedServer#4]
Most of dedic configs and their servers are one-two step
1. here is server instance
2. here is sh file with params, launch and play.

I don't want to tango around with my firewall and router to open ports just to see it didn't do anything.
I just wasted lot of time trying to run a server for my friends.

**Comment by titanbubu** [comment]
What games are you playing? Palworld, Ark, 7 days to die, Conan, Enshrouded - ALL require port forwarding. If you don't know how to port forward, you really shouldn't be doing dedicated servers. Just run the client-server.

**Comment by nikolai-imversed** [comment]
I am playing valheim and enshrouded but both of them didn't ask me to. If this game requires static IP, then provide it in the guide, if this game needs port forwarding, then either link the guide or tell people directly how it's done, because 3 separate people on discord tried to run the dedic and failed just there.

**Comment by titanbubu** [comment]
> I am playing valheim and enshrouded but both of them didn't ask me to. If this game requires static IP, then provide it in the guide, if this game needs port forwarding, then either link the guide or tell people directly how it's done, because 3 separate people on discord tried to run the dedic and failed just there.

Somehow you were able to skip port forwarding on two games that absolutely require it for dedicated servers. It makes me think you were either not on a truly dedicated server, or those games helped you by automatically adding firewall exceptions on your PC.

I disable the windows firewall on all my pcs because it is redundant and buggy.  

Abiotic requires ports 7777 (for the game) and 27015 (for the server browser) 

Static IPs do not matter - when you launch the server it will lock into whatever public IP you currently have.

**Comment by nikolai-imversed** [comment]
Valheim didn't ask for port forwarding, but I may be fault about it since it's been a long time I did it and you are right about enshrouded, indeed. Yet there is persistent issue about querying the server. I do know about 7777 and 27015 for steam query and that's where I start question things. Because both me and my friend started dedics, yet we couldn't find our own servers both in steam browser and in game browser. Mine won't query but I think it's mostly because of the firewall, as you said, might be buggy. But after some long time waiting I finally seen his. Still makes me wonder wtf was wrong, and static IP just might be an excuse for better indexing on steam browser or something, even tho it's really not matter at all 🤷🏼

**Comment by OfTheWild** [comment]
TCP or UDP? Firewall rules need to allow inbound on 7777 and outbound on 27015? Seems like this should be in the details of the install guide but i cant seem to find it mentioned or in the faq.
